class AppSecrets{
  static const supabaseUrl = 'https://oozwxrysvpdjrrpvvgsi.supabase.co';
  static const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vend4cnlzdnBkanJycHZ2Z3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTY5MjEsImV4cCI6MjA2MzczMjkyMX0.o_8dodLPg6B_CxYjnMyo4krp8xVUWI21I0SOc6XqTzQ';
}